// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxw9gk7B2xVyVWo2Bl6wJJ3__nfs8gNFM',
    appId: '1:432551665352:web:162c2064f6ab08a97a8ffd',
    messagingSenderId: '432551665352',
    projectId: 'oof-fitnx',
    authDomain: 'oof-fitnx.firebaseapp.com',
    databaseURL: 'https://oof-fitnx-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'oof-fitnx.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcHPxKaC8uaXpvhKrvXBfoCqXT4XyxuXM',
    appId: '1:432551665352:android:8cbff0ef8d3005aa7a8ffd',
    messagingSenderId: '432551665352',
    projectId: 'oof-fitnx',
    databaseURL: 'https://oof-fitnx-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'oof-fitnx.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCl_u_SAsgXn9xl2SOOQ9l677iVsPemWd8',
    appId: '1:432551665352:ios:aa9d132cc63e63e07a8ffd',
    messagingSenderId: '432551665352',
    projectId: 'oof-fitnx',
    databaseURL: 'https://oof-fitnx-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'oof-fitnx.firebasestorage.app',
    iosBundleId: 'com.dezza.gym',
  );
}
