/// Instructional GIFs, bundled locally as assets (sourced from
/// fitnessprogramer.com) and keyed by exercise name — shown in the Tips
/// panel when a matching asset exists. Bundled rather than loaded over
/// the network so they work offline, load instantly, and aren't subject
/// to browser CORS restrictions on Flutter Web. Not every exercise has
/// a match; ones without one are simply absent from this map.
const Map<String, String> exerciseGifUrls = {
  'Bench Press': 'assets/exercise_gifs/Barbell-Bench-Press.gif',
  'Incline Bench Press': 'assets/exercise_gifs/Incline-Barbell-Bench-Press.gif',
  'Decline Bench Press': 'assets/exercise_gifs/Decline-Barbell-Bench-Press.gif',
  'Dumbbell Bench Press': 'assets/exercise_gifs/Dumbbell-Press-1.gif',
  'Incline Dumbbell Press': 'assets/exercise_gifs/Incline-Dumbbell-Press.gif',
  'Decline Dumbbell Press': 'assets/exercise_gifs/Decline-Dumbbell-Press.gif',
  'Push-Up': 'assets/exercise_gifs/Push-Up.gif',
  'Dumbbell Fly': 'assets/exercise_gifs/Dumbbell-Fly.gif',
  'Cable Fly': 'assets/exercise_gifs/Cable-Crossover.gif',
  'Chest Dip': 'assets/exercise_gifs/Chest-Dips.gif',
  'Machine Chest Press': 'assets/exercise_gifs/Chest-Press-Machine.gif',
  'Decline Push-Up': 'assets/exercise_gifs/Decline-Push-Up.gif',
  'Deadlift': 'assets/exercise_gifs/Barbell-Deadlift.gif',
  'Romanian Deadlift': 'assets/exercise_gifs/Barbell-Romanian-Deadlift.gif',
  'Sumo Deadlift': 'assets/exercise_gifs/Barbell-Sumo-Deadlift.gif',
  'Trap Bar Deadlift': 'assets/exercise_gifs/Trap-Bar-Deadlift.gif',
  'Rack Pull': 'assets/exercise_gifs/barbell-rack-pull.gif',
  'Good Morning': 'assets/exercise_gifs/Barbell-Good-Morning.gif',
  'Back Extension': 'assets/exercise_gifs/hyperextension.gif',
  'Pull-Up': 'assets/exercise_gifs/Pull-up.gif',
  'Chin-Up': 'assets/exercise_gifs/Chin-Up.gif',
  'Lat Pulldown': 'assets/exercise_gifs/Lat-Pulldown.gif',
  'Barbell Row': 'assets/exercise_gifs/Barbell-Bent-Over-Row.gif',
  'Pendlay Row': 'assets/exercise_gifs/Barbell-Pendlay-Row.gif',
  'Dumbbell Row': 'assets/exercise_gifs/Dumbbell-Row.gif',
  'T-Bar Row': 'assets/exercise_gifs/t-bar-rows.gif',
  'Seated Cable Row': 'assets/exercise_gifs/Seated-Cable-Row.gif',
  'Chest-Supported Row': 'assets/exercise_gifs/Dumbbell-Seal-Row.gif',
  'Face Pull': 'assets/exercise_gifs/Face-Pull.gif',
  'Inverted Row': 'assets/exercise_gifs/Inverted-Row.gif',
  'Superman': 'assets/exercise_gifs/Superman-exercise.gif',
  'Overhead Press': 'assets/exercise_gifs/Barbell-Shoulder-Press.gif',
  'Seated Dumbbell Press': 'assets/exercise_gifs/Dumbbell-Shoulder-Press.gif',
  'Arnold Press': 'assets/exercise_gifs/Arnold-Press.gif',
  'Push Press': 'assets/exercise_gifs/push-press-1.gif',
  'Landmine Press': 'assets/exercise_gifs/Landmine-Press.gif',
  'Lateral Raise': 'assets/exercise_gifs/Dumbbell-Lateral-Raise.gif',
  'Front Raise': 'assets/exercise_gifs/Dumbbell-Front-Raise.gif',
  'Rear Delt Fly': 'assets/exercise_gifs/cable-rear-delt-fly.gif',
  'Upright Row': 'assets/exercise_gifs/barbell-uprightrow.gif',
  'Shrug': 'assets/exercise_gifs/Barbell-Shrug.gif',
  'Pike Push-Up': 'assets/exercise_gifs/Pike-Push-up.gif',
  'Prone Reverse Fly': 'assets/exercise_gifs/Dumbbell-Reverse-Fly.gif',
  'Squat': 'assets/exercise_gifs/BARBELL-SQUAT.gif',
  'Back Squat': 'assets/exercise_gifs/BARBELL-SQUAT.gif',
  'Front Squat': 'assets/exercise_gifs/front-squat.gif',
  'Goblet Squat': 'assets/exercise_gifs/Dumbbell-Goblet-Squat.gif',
  'Hack Squat': 'assets/exercise_gifs/Barbell-Hack-Squat.gif',
  'Sissy Squat': 'assets/exercise_gifs/sissy-squat.gif',
  'Zercher Squat': 'assets/exercise_gifs/Zercher-Squat.gif',
  'Bulgarian Split Squat': 'assets/exercise_gifs/Dumbbell-Bulgarian-Split-Squat.gif',
  'Walking Lunge': 'assets/exercise_gifs/dumbbell-lunges.gif',
  'Reverse Lunge': 'assets/exercise_gifs/bodyweight-reverse-lunge.gif',
  'Step-Up': 'assets/exercise_gifs/Dumbeel-Step-Up.gif',
  'Leg Press': 'assets/exercise_gifs/Leg-Press.gif',
  'Leg Extension': 'assets/exercise_gifs/LEG-EXTENSION.gif',
  'Leg Curl': 'assets/exercise_gifs/Leg-Curl.gif',
  'Nordic Curl': 'assets/exercise_gifs/Nordic-Hamstring-Curl.gif',
  'Hip Thrust': 'assets/exercise_gifs/Barbell-Hip-Thrust.gif',
  'Glute Bridge': 'assets/exercise_gifs/Glute-Bridge-.gif',
  'Calf Raise': 'assets/exercise_gifs/Dumbbell-Calf-Raise.gif',
  'Seated Calf Raise': 'assets/exercise_gifs/Barbell-Seated-Calf-Raise.gif',
  'Bicep Curl': 'assets/exercise_gifs/Barbell-Curl.gif',
  'Hammer Curl': 'assets/exercise_gifs/Hammer-Curl.gif',
  'Preacher Curl': 'assets/exercise_gifs/Dumbbell-Preacher-Curl.gif',
  'Concentration Curl': 'assets/exercise_gifs/Concentration-Curl.gif',
  'Cable Curl': 'assets/exercise_gifs/cable-curl.gif',
  'EZ Bar Curl': 'assets/exercise_gifs/Reverse-Grip-EZ-Bar-Curl.gif',
  'Reverse Curl': 'assets/exercise_gifs/Barbell-Reverse-Curl.gif',
  'Wrist Curl': 'assets/exercise_gifs/barbell-Wrist-Curl.gif',
  'Tricep Pushdown': 'assets/exercise_gifs/One-arm-triceps-pushdown.gif',
  'Skull Crusher': 'assets/exercise_gifs/Barbell-Reverse-Grip-Skullcrusher-1.gif',
  'Overhead Tricep Extension': 'assets/exercise_gifs/High-Pulley-Overhead-Tricep-Extension.gif',
  'Cable Overhead Extension': 'assets/exercise_gifs/High-Pulley-Overhead-Tricep-Extension.gif',
  'Close-Grip Bench Press': 'assets/exercise_gifs/Close-Grip-Bench-Press.gif',
  'Tricep Dip': 'assets/exercise_gifs/Triceps-Dips.gif',
  'Diamond Push-Up': 'assets/exercise_gifs/Diamond-Push-up.gif',
  'Plank': 'assets/exercise_gifs/plank.gif',
  'Side Plank': 'assets/exercise_gifs/Side-Plank-Leg-Raises.gif',
  'Crunch': 'assets/exercise_gifs/Crunch.gif',
  'Sit-Up': 'assets/exercise_gifs/Sit-ups.gif',
  'Hanging Leg Raise': 'assets/exercise_gifs/Hanging-Leg-Raises.gif',
  'Hanging Knee Raise': 'assets/exercise_gifs/Hanging-Knee-Raises.gif',
  'Russian Twist': 'assets/exercise_gifs/Russian-Twist.gif',
  'Cable Woodchopper': 'assets/exercise_gifs/Standing-Cable-High-To-Low-Twist.gif',
  'Ab Wheel Rollout': 'assets/exercise_gifs/Ab-Wheel-Rollout.gif',
  'Mountain Climber': 'assets/exercise_gifs/Mountain-climber.gif',
  'Dead Bug': 'assets/exercise_gifs/Dead-Bug.gif',
  'Bicycle Crunch': 'assets/exercise_gifs/Bicycle-Crunch.gif',
  'V-Up': 'assets/exercise_gifs/Jackknife-Sit-ups.gif',
  'Pallof Press': 'assets/exercise_gifs/Cable-Half-Kneeling-Pallof-Press.gif',
  'Kettlebell Swing': 'assets/exercise_gifs/Kettlebell-Swings.gif',
  'Clean and Jerk': 'assets/exercise_gifs/clean-and-jerk.gif',
  'Snatch': 'assets/exercise_gifs/Barbell-Snatch.gif',
  'Power Clean': 'assets/exercise_gifs/Power-Clean-.gif',
  "Farmer's Carry": 'assets/exercise_gifs/Farmers-walk_Cardio.gif',
  'Battle Ropes': 'assets/exercise_gifs/Battle-Rope.gif',
  'Box Jump': 'assets/exercise_gifs/Box-Jump-1-to-2.gif',
  'Burpee': 'assets/exercise_gifs/burpees.gif',
  'Wall Ball': 'assets/exercise_gifs/wall-ball.gif',
  'Thruster': 'assets/exercise_gifs/thruster.gif',
  'Turkish Get-Up': 'assets/exercise_gifs/Turkish-Get-Up-Squat-style.gif',
  'Medicine Ball Slam': 'assets/exercise_gifs/Medicine-ball-Overhead-Slam-exercise.gif',
  'Sled Push': 'assets/exercise_gifs/plate-push.gif',
};
